version: "3"
services:
  # ポートの対応付け
  # ファイル共有　docker toolboxでは c/Users 下のみ
  # https://team-lab.github.io/skillup/step1/07-db.html
  # https://team-lab.github.io/skillup/step1/04a-docker.html
  postgres11:
    build: .
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=Sample
    ports:
      - "8081:5432"
    volumes:
      - /c/Users/initdb:/docker-entrypoint-initdb.d
    hostname: postgres
    restart: always

  pgadmin4:
    image: dpage/pgadmin4:latest
#    container_name: pgadmin4
    ports:
      - 8082:80
#    volumes:
#      - ./pgadmin:/var/lib/pgadmin/storage
    environment:
      PGADMIN_DEFAULT_EMAIL: root
      PGADMIN_DEFAULT_PASSWORD: root
    hostname: pgadmin
    restart: always